version: '3'
services:
  db:
      image: postgres:alpine
      restart: always
      network_mode: host
      environment:
        POSTGRES_PASSWORD: postgres
  server: 
      build: ./
      network_mode: host
      depends_on: [db]
    